name: process_pyrad
channels:
  - defaults
  - pip:
    - attrs==21.4.0
    - click==8.0.3
    - connected-components-3d==3.8.0
    - deprecated==1.2.13
    - docopt==0.6.2
    - filelock==3.4.2
    - grpcio==1.43.0
    - imageio==2.14.0
    - jsonschema==4.4.0
    - msgpack==1.0.3
    - networkx==2.6.3
    - numpy==1.21.5
    - packaging==21.3
    - pillow==8.4.0
    - protobuf==3.19.3
    - pykwalify==1.8.0
    - pyparsing==3.0.6
    - pyradiomics==3.0.1
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pywavelets==1.2.0
    - pyyaml==6.0
    - ray==1.9.2
    - redis==4.1.1
    - ruamel-yaml==0.17.20
    - ruamel-yaml-clib==0.2.6
    - scikit-image==0.19.1
    - scipy==1.7.3
    - simpleitk==2.0.2
    - six==1.16.0
    - tifffile==2021.11.2
    - wrapt==1.13.3


